### ISSUE TITLE
Item capability addition support.

### ISSUE THREAD

**Issue by AutumnalModding** [Prunoideae/PowerfulJS#1]
Title.
Pretty, pretty, pretty please; this would be amazing.

**Comment by Prunoideae** [comment]
Check out [this](https://github.com/Prunoideae/PowerfulJS/blob/1.19.2/common/src/main/java/com/prunoideae/powerfuljs/mixins/ItemMixin.java) and [this](https://github.com/Prunoideae/PowerfulJS/blob/1.19.2/common/src/main/java/com/prunoideae/powerfuljs/mixins/ItemBuilderMixin.java)

**Comment by DoubleHypercube** [comment]
Can you modify existing items with it?
I didn't see an event for that.

**Comment by Prunoideae** [comment]
An example to make `apple` wearable but not unequippable on Curio's belt slot:

```js
//startup_scripts
ItemEvents.modification(event => {
	event.modify("apple", modify => {
		modify.attachCapability(
			CuriosCapabilityBuilder.CURIOS.itemStack()
				.canEquip((stack, context) => true)
				.canUnequip((stack, context) => false)
				.modifyAttribute("generic.movement_speed", "apple_speed", 0.1, "multiply_total")
		)
	})
})
```

```js
//server_scripts
ServerEvents.tags('item', event => {
	event.add("curios:belt", "minecraft:apple")
})
```

Complete documentation is still on the way, I need to finish documenting for KubeJS's events first.
